sudo: false
dist: trusty

services:
  - docker

script:
  - docker build -t bmstu-ical .
  - docker run -d --name bmstu-ical bmstu-ical
  - docker start bmstu-ical
  - docker exec -it bmstu-ical npm test
